### ISSUE TITLE
Router - Error since 5.0 version

### ISSUE THREAD

**Issue by mhosman** [datorama/akita#399] opened 2020-04-09 20:57 UTC
Hi, since 5.0 when I try to navigate the first time to another page, I get:

```
core.js:6189 ERROR TypeError: Cannot read property 'state' of undefined
    at RouterService.serializeRoute (datorama-akita-ng-router-store.js:413)
    at RouterService.resolveEnd (datorama-akita-ng-router-store.js:389)
    at SafeSubscriber._next (datorama-akita-ng-router-store.js:371)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at Subject.next (Subject.js:39)
    at Router.triggerEvent (router.js:7344)
    at TapSubscriber._tapNext (router.js:7107)
```

I don't have any other description of the error (don't know where the error is being generated).

**Comment by NetanelBasal** [comment] 2020-04-10 05:13
Can you reproduce it [here](https://stackblitz.com/edit/akita-ng-router), please?

**Comment by mhosman** [comment] 2020-04-10 18:21
The app is big and the error is not specific (Does not indicate where the error is being generated)... so... I don't know how to reproduce this in a small configuration.

**Comment by NetanelBasal** [comment] 2020-04-11 17:14
Sorry, but in order to resolve it, I need to understand the issue.

**Comment by NetanelBasal** [comment] 2020-04-27 14:52
Should be fixed with 5.1.0

**Closed by NetanelBasal** 2020-04-27 14:52 UTC
Labels: comp: NgRouter

**Comment by mhosman** [comment] 2020-04-29 16:28
Still happening...

```
core.js:6210 ERROR TypeError: Cannot read property 'state' of undefined
    at RouterService.serializeRoute (datorama-akita-ng-router-store.js:217)
    at SafeSubscriber._next (datorama-akita-ng-router-store.js:189)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:183)
    at SafeSubscriber.next (Subscriber.js:122)
    at Subscriber._next (Subscriber.js:72)
    at Subscriber.next (Subscriber.js:49)
    at Subject.next (Subject.js:39)
    at TapSubscriber._tapNext (router.js:7066)
    at TapSubscriber._next (tap.js:40)
    at TapSubscriber.next (Subscriber.js:49)
```

**Comment by NetanelBasal** [comment] 2020-04-30 04:21
> Sorry, but in order to resolve it, I need to understand the issue.

This is relevant again ^^

**Comment by mhosman** [comment] 2020-04-30 17:40
@NetanelBasal, the error ocurrs only when I change the route for the first time (no error at init and no error after first route change).

**Comment by NetanelBasal** [comment] 2020-05-01 04:00
Try to reproduce it, please.

**Comment by vervallsweg** [comment] 2020-09-17 10:20
I'm new to akita, and have the same problem. I really don't know what causes this. However, the error message is quite clear.

libs/akita-ng-router-store/src/lib/router.service.ts
```TypeScript
private serializeRoute(navigationEvent: RoutesRecognized | GuardsCheckEnd | ResolveEnd): RouterState {
    ...
    return {
      ...
      state: {
        ...
        navigationExtras: this.router.getCurrentNavigation().extras.state,
      },
    };
  }
```
`this.router.getCurrentNavigation().extras` can be undefined. Simply returning an empty object if it is undefined resolves this. The router-store no longer crashes and continues to operate without any issues.

```TypeScript
navigationExtras: this.router.getCurrentNavigation().extras ? this.router.getCurrentNavigation().extras.state : {},
```

Yes this is not a great fix, one should investigate what is causing `this.router.getCurrentNavigation().extras` to be undefined. Personally I don't understand akita, or the ng-router well enough yet to do it.

PS: I did fork it with a fix, however I cannot even use the locally compiled library due to some weird rxjs dependency error. Aaaand the github action will just fail [in my fork](https://github.com/vervallsweg/akita/runs/1125764680?check_suite_focus=true), without any changes to the repo. Tests pass though 🤡
So if someone wants fix the build issues, you'd have [a workaround](https://github.com/vervallsweg/akita/commit/e3239e2757d4aeff6cf7a9518a710019d2fb9a6e) for that.

**Comment by NetanelBasal** [comment] 2020-09-17 11:00
Do you want to create a PR?
