### ISSUE TITLE
[Schematics] Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by fstodulski** [datorama/akita#737] opened 2021-08-31 09:03 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior
For newly created project:
`ng add @datorama/akita` throws an error:
`: Cannot find module 'bluebird'`

```
Require stack:
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@schematics/update/node_modules/pacote/extract.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@schematics/update/node_modules/pacote/index.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@schematics/update/update/npm.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/schematics-utilities/dist/package_update/npm.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/schematics-utilities/dist/package_update/index.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/schematics-utilities/dist/index.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@datorama/akita/schematics/ng-add/index.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@angular-devkit/schematics/tools/export-ref.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@angular-devkit/schematics/tools/index.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@angular/cli/utilities/json-schema.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@angular/cli/models/command-runner.js
- /Users/franciszekstodulski/develop/testing-datorama/node_modules/@angular/cli/lib/cli/index.js
- /Users/franciszekstodulski/.nvm/versions/node/v14.17.0/lib/node_modules/@angular/cli/lib/init.js
- /Users/franciszekstodulski/.nvm/versions/node/v14.17.0/lib/node_modules/@angular/cli/bin/ng
See "/private/var/folders/nr/vzhtlbf91617mjw4_s04r4900000gq/T/ng-cujUr8/angular-errors.log" for further details.
```

## Expected behavior
Adding Akita to angular's project.

## Minimal reproduction of the problem with instructions

Use Angular CLI: 12.2.3
Create a new workspace with `ng new`.
Try to add Akita with `ng add @datorama/akita` command

For bug reports please provide the _STEPS TO REPRODUCE_ and if possible a _MINIMAL DEMO_ of the problem via
https://stackblitz.com or similar (you can use this template as a starting point: https://stackblitz.com/github/NetanelBasal/akita-issue-seed).

## What is the motivation / use case for changing the behavior?
Well. Can't add Akita to any newly created projects.

## Environment

<pre><code>
Angular CLI: 12.2.3
Package Manager: npm 7.16.0
@angular-devkit/architect       0.1202.3
@angular-devkit/build-angular   12.2.3
@angular-devkit/core            12.2.3
@angular-devkit/schematics      12.2.3
@schematics/angular             12.2.3
rxjs                            6.6.7
typescript                      4.3.5

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 14.17.0
- Platform:  OS: darwin x64

Others:

</code></pre>

**Comment by NetanelBasal** [comment] 2021-08-31 19:18
Duplicate of #727

**Closed by NetanelBasal** 2021-08-31 19:18 UTC
