### ISSUE TITLE
[dependencies] tslib >= 1.7.0 < 2

### ISSUE THREAD

**Issue by C0ZEN** [datorama/akita#486] opened 2020-07-08 12:40 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

The version dependency of `tslib` for akita is `< 2`.

## Expected behavior

Is it possible to use it with the version `2.0.0`?
I am wondering if this is still on purpose due to an incompatibility or if you could simply update it to allow to be compatible with the version `2.0.0`.

## What is the motivation / use case for changing the behavior?

Upgrading to Angular 10 on my project with the CLI throw an error.
Using the flag `force` allow nevertheless to update the dependency.

Note that even if Akita dependency seems to be incompatible with tslib I already have the `2.0.0` version and everything seems fine.

## Example

This command:
`ng update @datorama/akita @datorama/akita-cli @datorama/akita-ngdevtools`

Produce this error:
```
Package "@datorama/akita-ngdevtools" has an incompatible peer dependency to "tslib" (requires "^1.10.0", would install "2.0.0")
Package "@datorama/akita" has an incompatible peer dependency to "tslib" (requires ">= 1.7.0 < 2", would install "2.0.0")
```

## Environment

<pre><code>
Angular version: 10.0.2
</code></pre>

**Comment by NetanelBasal** [comment] 2020-07-08 13:04
@xbaun what do u think?

**Comment by xbaun** [comment] 2020-07-08 15:31
It seems that typescript must be upgraded to >3.8, to use tslib 2.0.0: https://github.com/microsoft/tslib/releases/tag/2.0.0

**Comment by xbaun** [comment] 2020-07-08 17:36
By requiring tslib 2.0.0 or higher we will probably break current projects based on older ts versions. Best option would be to compile Akita without `--importHelpers` flag, thus directly generating the helper functions and removing the tslib peer dependency.

**Comment by C0ZEN** [comment] 2020-07-08 19:57
@xbaun thank you for the insight.
If you do not plan to change the compilation method is it still required to disallow `tslib` on `2.0.0` version?
I am not sure, but I think that if you change the restriction to higher version it will not force to download the `2.0.0` since it will meet the `>= 1.7.0` range for older versions and also avoid this error.
Also, if this was mentioned in the documentation for older versions that `tslib` should be set below the `2.0.0` version it would avoid potential mistakes when upgrading.
What do you think? Thanks.

**Comment by xbaun** [comment] 2020-07-08 20:34
> I am not sure, but I think that if you change the restriction to higher version it will not force to download the `2.0.0` since it will meet the `>= 1.7.0` range for older versions and also avoid this error.

The problem would be if Akita is compiled with a ts version lower than 3.9 (what is currently the case), it would require a tslib version < 2.0.0 to be installed which isn't compatible to 2.0.0 because of breaking changes in the helper functions. So if a project using Akita is relaying on tslib >= 2.0.0 (thus a newer ts version), then Akita would probably break by importing the wrong tslib version expecting the old helper functions. And the other way around.

So I would enable inlining the helper functions so that the dependency to any specific tslib version is removed. Projects using Akita can then choose any ts/tslib version they need.

**Comment by deceptiveSimplicity** [comment] 2020-08-07 09:03
Any update on this?

**Comment by oliveti** [comment] 2020-08-18 14:59
Hello,

As state by @C0ZEN, if you force the update angular 10 and akita are working nice together.
But according to @xbaun, it seems it should not work.

How could we explain this ?

**Comment by C0ZEN** [comment] 2020-08-18 15:10
@oliveti not work with older versions only.

**Comment by C0ZEN** [comment] 2020-08-18 15:35
@oliveti this issue (which is not a bug but a feature-request) is only possible when you have tslib on 2.X.X on your project and you use Akita which requires > 2.

**Comment by hakimio** [comment] 2020-09-15 06:53
@xbaun can we do sth about this? Akita seems to work fine with tslib v2, TS v4 and Angular v10.1, but the peer dependency warning is pretty annoying. Maybe you could release a new majore version which depends on tslib v2 and TS > 3.9 ?

**Comment by Wintermute79** [comment] 2020-12-10 17:31
I recently started a new project in Angular 10. This issue is preventing me - and possibly many others - from using Akita.

**Comment by hakimio** [comment] 2020-12-10 19:32
@Wintermute79 how is it preventing you from using Akita? It's just a harmless warning.

**Comment by NetanelBasal** [comment] 2020-12-11 07:08
I'm going to upgrade everything to the latest versions and release Akita v6. It'll take some time, but you can ignore the warning for now.

**Comment by Wintermute79** [comment] 2020-12-11 11:45
> @Wintermute79 how is it preventing you from using Akita? It's just a harmless warning.

When trying to install Akita via `npm install @datorama/akita` _from within the Angular 10 project directory_, it wont complete, giving the following errors:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: my-app@1.0.0
npm ERR! Found: tslib@2.0.3
npm ERR! node_modules/tslib
npm ERR!   tslib@"^2.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@">= 1.7.0 < 2" from @datorama/akita@4.23.2
npm ERR! node_modules/@datorama/akita
npm ERR!   @datorama/akita@"^4.22.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

When I realised the cause and tried again from another path, it succeeded. So my apologies for being not clear enough in my earlier post.

**Comment by hakimio** [comment] 2020-12-11 12:03
@Wintermute79 seems like [npm bug](https://github.com/npm/cli/issues/2000). Try to update your npm cli.

**Comment by Wintermute79** [comment] 2020-12-11 12:14
@hakimio thanks for the hint; I guess I will switch to Yarn then.

**Comment by NetanelBasal** [comment] 2021-01-16 19:07
The upgrade is released with v6.

**Closed by NetanelBasal** 2021-01-16 19:07 UTC
Labels: In progress
