### ISSUE TITLE
Cannot assign to read only property 'currentPage' of object '[object Object]'

### ISSUE THREAD

**Issue by jeremiahverbaSAE** [datorama/akita#371] opened 2020-02-06 20:44 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

`this.paginatorRef.nextPage();`
`this.paginatorRef.setFirstPage()`
The 2 preceding calls results in: 
`Cannot assign to read only property 'currentPage' of object '[object Object]'`

## Expected behavior

`this.paginatorRef.nextPage();`
`this.paginatorRef.setFirstPage()`
The 2 preceding calls results in the desired page being set in the paginator and the observable with proper data being emitted.

## Minimal reproduction of the problem with instructions
Given: 
`export const COMMENTS_PAGINATOR = new InjectionToken('COMMENTS_PAGINATOR', {
  providedIn: 'root',
  factory: () => {
    const commentsQuery = inject(CommentsQuery);
    return new PaginatorPlugin(commentsQuery).withControls().withRange();
  }
});`
In my component's constructor...
`constructor(
    @Inject(COMMENTS_PAGINATOR) public paginatorRef: PaginatorPlugin<CommentsState>,`

if anywhere in my component I call these:
`this.paginatorRef.nextPage();`
`this.paginatorRef.setFirstPage()`
The 2 preceding calls results in: 
`Cannot assign to read only property 'currentPage' of object '[object Object]'`

## What is the motivation / use case for changing the behavior?

Just want to set the page or go to the next page

## Environment
all

**Comment by NetanelBasal** [comment] 2020-02-07 06:38
Why do you call them together? It doesn't make sense. First, you're asking for the next page, and immediately you're changing it to the first page?

**Comment by jeremiahverbaSAE** [comment] 2020-02-07 13:36
I'm not calling them together. I'm just showing that either of those calls results in the same error. I have one of them on a button click to load the next page.  I tried the setFirstPage() call in the subscribe call back just to see if setting a first page was required before asking for the next page.  They're only "together" in this bug report.

**Comment by NetanelBasal** [comment] 2020-02-07 14:14
Works for me. Can you reproduce it, please?

**Comment by NetanelBasal** [comment] 2020-02-14 09:54
You can see a working example here: https://github.com/datorama/akita/blob/master/angular/playground/src/app/contacts/contacts-page/contacts-page.component.html#L60-L77

**Comment by maku** [comment] 2020-02-17 14:09
@NetanelBasal I try to change the state managment solution for an app from ngxs to akita and I stumbled also over the error 
`ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property '...' of object '[object Object]'`

Is there anything to pay attention to when using akita?

**Comment by NetanelBasal** [comment] 2020-02-17 14:25
It seems like you mutating the object. I need a reproduction so I could help.

**Comment by maku** [comment] 2020-02-17 14:26
@NetanelBasal I am aware that I mutate the object. But how does akita manipulate the object I put in the store?

**Comment by NetanelBasal** [comment] 2020-02-17 14:32
Can you show the code the mutates it, please?

**Comment by maku** [comment] 2020-02-17 14:34
@NetanelBasal It occurs in a complex logic spanned over class instances / functions calls. It is legacy functionality which is also used in a nodejs program. But the data manipulation was fine when I used in with ngxs. So I would be interested in how akita manipulates the objects in the store so that a direct manipulation is not possible (is this the case?)

**Comment by NetanelBasal** [comment] 2020-02-17 14:38
I guess you're not using deep freeze with ngxs.

**Comment by maku** [comment] 2020-02-17 14:42
@NetanelBasal no I do not. Does akita some magic under the hood?

**Comment by NetanelBasal** [comment] 2020-02-17 14:45
No, in dev mode, we deep freeze the store, so that you don't mutate it. See https://netbasal.gitbook.io/akita/getting-started/production-mode

**Comment by maku** [comment] 2020-02-17 14:48
The (temporary) solution would be to provide a "deepFreezeFn" in the StoreConfig which does nothting, right (deepFreezeFn: obj => obj)?

**Comment by NetanelBasal** [comment] 2020-02-17 14:50
Yes

**Comment by maku** [comment] 2020-02-17 15:32
@NetanelBasal thank you

**Comment by jeremiahverbaSAE** [comment] 2020-02-17 17:15
I am / was trying to use NgEntityService with PaginationPlugin.  I see here: https://github.com/datorama/akita/issues/319  that this is not possible.  I was able to get past the issue I opened here by using the above deepFreezeFn work around, but then I had other state issues, most likely due to the incompatibility with NgEntityService and PaginatorPlugin.  Refactoring to remove NgEntityService from the mix to see if that solves it all.

**Comment by loxy** [comment] 2020-02-20 12:35
I also have a problem with `Cannot assign to read only property 'tView' of object '[object Object]'`
You can find a sample repo here: https://gitlab.com/loxy/angular-portal-bug

Basically I use the CDK to dynamically render components in portals. The list of components come from a service. If I use a normal `BehaviorSubject` it works:
https://gitlab.com/loxy/angular-portal-bug/-/blob/master/src/app/active-components-simple.service.ts#L12

But if I use the store from Akita it crashes:
https://gitlab.com/loxy/angular-portal-bug/-/blob/master/src/app/state/loader.service.ts#L12

There was also a problem on NgRx: https://github.com/ngrx/platform/issues/2109
Maybe it is somehow related...

But maybe I also misuse your library. I any case it has something to do with "deep freeze", because if I inspect `def.tView` with `Object.getOwnPropertyDescriptor` in `getOrCreateTComponentView (core.js)` writable is set to false...

Any hints?

**Comment by NetanelBasal** [comment] 2020-02-20 12:39
Someone is mutating the component state. To solve it you can disable `deepFreeze` in your store. https://github.com/datorama/akita/issues/371#issuecomment-587028526

**Comment by loxy** [comment] 2020-02-20 15:23
Yes, Ivy...

**Comment by NetanelBasal** [comment] 2020-02-21 05:53
I'm closing the issue. If some third party mutates the state, and you still want to use a store, you should disable `deepFreeze`, as we discussed here.

**Closed by NetanelBasal** 2020-02-21 05:53 UTC
Labels: state: Needs repro
